### ISSUE TITLE
Smarthings fails to set up

### ISSUE THREAD

**Issue by convicte** [schmittx/home-assistant-smartthings#1]
![image](https://github.com/schmittx/home-assistant-smartthings/assets/78666770/a728ff17-a205-4e32-a439-e26fc3d348ac)

Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 02:46:58 (3 occurrences)
Last logged: 02:48:31

Error setting up entry My home for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings/__init__.py", line 193, in async_setup_entry
    broker = await hass.async_add_import_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceBroker.__init__() missing 1 required positional argument: 'scenes'

I've tried setting it up anew multiple times, including removing the integration all together and recreating the token.

Currently, running HA 2024.5.2 and smarthings 1.0.5 without much luck

Assistance would be appreciated!

**Comment by convicte** [comment]
@schmittx if you would find a second to take a look, I'd greatly appreciate it. 

Cheers!!

**Comment by schmittx** [comment]
Fixed in [1.0.6 release](https://github.com/schmittx/home-assistant-smartthings/releases/tag/1.0.6)

**Comment by convicte** [comment]
@schmittx 
Thank you so very much for your efforts.

After having installed the latest version the integration indeed is setting up again but for some reason it creates only one entity per device which is temperature.
This is regardless if the device has a temperature sensor or not.

No entities for climate in an AC or for other settings in the fridge. Would you mind looking into it?

Thank you!

**Comment by schmittx** [comment]
Many of the entity types have been removed in this integration as I don't personally have any of the associated appliances. In other words, the support and functionality is very specific to my use case and I have no plans to expand the scope. You're welcome to fork the repo though and expand on it for your own use case.

**Comment by convicte** [comment]
Thanks for the background.

I am curious though - they worked for 2024.4.X HA on 1.0.5 and stopped when moving to 2024.5.X. Then you've made a modification to 1.0.6 which fixed the basic initiation of the integration, though majority of entities are gone within devices.

Without removing code which previously worked, how did that happen?

I recognize what you said, though I don't have the skills to maintain my own fork and was hoping to continue using what worked, with no expectation of any new capabilities.

Would appreciate your thoughts!
