### ISSUE TITLE
Devices are not shown or not all sensors show up correctly

### ISSUE THREAD

**Issue by alrassia** [schmittx/home-assistant-smartthings#2]
First off thank you for your effort,  its really nice to see the smartthings integration being picked up especially not that the official one is basically no longer maintained.

I just installed the integration on my docker HA setup (version 2024.6.3) through HACS, setting up went fine.

I have my Samsung refrigerator, current television and old no longer used TV setup in smartthings. The fridge is shown as a device in the integration but sensors are not working neither of the TVs are shown as devices in the integration but do seem to show up as detected in the logs.

For the fridge temperature measurement is shown with a value unknown but nothing else. Looking at the device capabilities (see attached device.attributes.json) a few more should show up. At least the contact sensor is a standard capability I believe.

fridge: [Device Attributes.json](https://github.com/user-attachments/files/15926858/Device.Attributes.json)

The television does not show up, but the logs seem to indicate it is detected 

television: [Device Attributes tv.json](https://github.com/user-attachments/files/15926938/Device.Attributes.tv.json)

Any ideas what is going wrong with the devices?

Looking in the logs I see the following messages:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:766
integration: Sensor (documentation, issues)
First occurred: 1:13:41 PM (4 occurrences)
Last logged: 1:13:41 PM

Platform smartthings does not generate unique IDs. ID fa45ec93-b07e-2548-f7e8-0697243098c6-smartthings-temperature already exists - ignoring sensor.refrigerator_temperature_measurement

Logger: custom_components.smartthings.smartapp
Source: custom_components/smartthings/smartapp.py:337
integration: SmartThings (documentation, issues)
First occurred: 1:13:41 PM (1 occurrences)
Last logged: 1:13:41 PM

Failed to create subscription for 'samsungce.softwareUpdate' under app '43e62ebc-2158-4c77-8c37-d654bf6ddf71': Unprocessable Entity (422): {"requestId": "1499796930955481181", "error": {"code": "LimitError", "message": "subscription limit exceeded", "details": []}}

Logger: custom_components.smartthings.smartapp
Source: custom_components/smartthings/smartapp.py:390
integration: SmartThings (documentation, issues)
First occurred: 1:13:40 PM (1 occurrences)
Last logged: 1:13:40 PM

Some device attributes may not receive push updates and there may be subscription creation failures under app '43e62ebc-2158-4c77-8c37-d654bf6ddf71' because 46 subscriptions are required but there is a limit of 40 per app

full log: [home-assistant_smartthings_2024-06-21T11-29-35.771Z.log](https://github.com/user-attachments/files/15926944/home-assistant_smartthings_2024-06-21T11-29-35.771Z.log)

**Comment by schmittx** [comment]
Sorry, but this integration is heavily customized for my personal setup and only supports the specific devices I use. Unfortunately, I don't use TVs or any refrigerators through SmartThings so no future support is planned for these. You're welcome to fork and tinker for your own setup though.
